---
title: "Trash Wheel"
output: html_document
date: "2024-03-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggstream)
```


```{r}
trashwheel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-03-05/trashwheel.csv')
```


```{r}
trash_long<-trashwheel|>
  pivot_longer(cols=PlasticBottles:SportsBalls, names_to="type", values_to="count")|>
  group_by(Name, Date, type)|>
  summarize(bigcount = sum(count))
```

```{r}
trash_long|>
  mutate(date_obj =as_date(Date)|>
  ggplot(aes(x = date_obj, y=bigcount, fill=type, color = type))+
  geom_density(stat="identity") + 
  scale_y_log10()
    
```


```{r}
library(tidyverse)
library(here)

working_dir <- here::here("data", "2024", "2024-03-05")

# Download the csv files from https://docs.google.com/spreadsheets/d/1b8Lbe-z3PNb3H8nSsSjrwK2B0ReAblL2/edit#gid=1143432795

mrtrash <- read_csv("mrtrashwheel.csv")
professortrash <- read_csv("professortrash.csv")
captaintrash <- read_csv("captaintrash.csv")
gwynndatrash <- read_csv("gwynndatrash.csv")


# Check the files
glimpse(mrtrash)
glimpse(professortrash)
glimpse(captaintrash)
glimpse(gwynndatrash)

# Remove empty rows and columns

mrtrash <- head(mrtrash, -1)
mrtrash <- mrtrash[-c(15:16)]


# Rename columns so they don't have spaces

colnames(mrtrash)

mrtrash <- mrtrash %>% 
  rename(
    Weight = "Weight (tons)",
    Volume = "Volume (cubic yards)",
    PlasticBottles = "Plastic Bottles",
    CigaretteButts = "Cigarette Butts",
    GlassBottles = "Glass Bottles",
    PlasticBags = "Plastic Bags",
    SportsBalls = "Sports Balls",
    HomesPowered = "Homes Powered*"
  )

colnames(professortrash)

professortrash <- professortrash %>% 
  rename(
    Weight = "Weight (tons)",
    Volume = "Volume (cubic yards)",
    PlasticBottles = "Plastic Bottles",
    CigaretteButts = "Cigarette Butts",
    GlassBottles = "Glass Bottles",
    PlasticBags = "Plastic Bags",
    HomesPowered = "Homes Powered*"
  )

colnames(captaintrash)

captaintrash <- captaintrash %>% 
  rename(
    Weight = "Weight (tons)",
    Volume = "Volume (cubic yards)",
    PlasticBottles = "Plastic Bottles",
    CigaretteButts = "Cigarette Butts",
    PlasticBags = "Plastic Bags",
    HomesPowered = "Homes Powered*"
  )

colnames(gwynndatrash)

gwynndatrash <- gwynndatrash %>% 
  rename(
    Weight = "Weight (tons)",
    Volume = "Volume (cubic yards)",
    PlasticBottles = "Plastic Bottles",
    CigaretteButts = "Cigarette Butts",
    PlasticBags = "Plastic Bags",
    HomesPowered = "Homes Powered*"
  )

# Add a column with the name of the trash wheel, and columns with "NA" where the dataset doesn't have that information

mrtrash <- data.frame(ID = "mister", Name = "Mister Trash Wheel", mrtrash)

# Add SportsBalls to professor
professortrash <- data.frame(ID = "professor", Name = "Professor Trash Wheel", SportsBalls = NA, professortrash)

# Add SportsBalls and GlassBottles to captain and gwynnda
captaintrash <- data.frame(ID = "captain", Name = "Captain Trash Wheel", SportsBalls = NA, GlassBottles = NA, captaintrash)
gwynndatrash <- data.frame(ID = "gwynnda", Name = "Gwynnda Trash Wheel", SportsBalls = NA, GlassBottles = NA, gwynndatrash)

# Join the dataframes together

trashwheel <- rbind(mrtrash, professortrash, captaintrash, gwynndatrash)



readr::write_csv(
  trashwheel,
  fs::path(working_dir, "trashwheel.csv")
)
```

